### PR TITLE
hidden input field

### PR DESCRIPTION
**Pull request by victhevenot**
delete and patch requests @jmburges @SophieDeBenedetto @StevenNunez

### CODE REVIEW

**Comment by SophieDeBenedetto** [comment]
@vicfriedman in order for `delete` and `patch` to work w/ hidden input field, `config.ru`  file must include this line: `use Rack::MethodOverride`

**Comment by victhevenot** [comment]
adding now!

**Comment by victhevenot** [comment]
please review again @SophieDeBenedetto

**Comment by octosteve** [comment]
@vicfriedman YEYEYEY

**Pull request merged**
